main:
  - name: Research
    url: /research/
    weight: 10
  - name: People
    url: /people/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Projects & Software
    url: /projects/
    weight: 40
  - name: News
    url: /news/
    weight: 50
  - name: Join / Contact
    url: /join/
    weight: 60
